project:
  type: website
  output-dir: docs
  pre-render:
    - code/gen-week-files-from-course-schedule.R
  render:
    - index.qmd
    - syllabus.qmd
    - weeks/*.qmd
    - business-report/*.qmd
    - instructions/*.qmd
    - homework/*.qmd
    - slides/*.qmd
  


engine: knitr
website:
  page-navigation: true
  title: "STAT 349 - Spring 2025"
  description: "Homepage for STAT 349 - Technical Communication."
  site-url: "https://unl-statistics.github.io/stat349"

  repo-url: https://github.com/unl-statistics/stat349
  repo-actions: [edit, issue]

  open-graph: true

  twitter-card:
    creator: "@srvanderplas"
    image: "images/twitter-card.png"

  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2025, Susan Vanderplas"
    background: "#D3D3D3"

  sidebar:
    background: "#D3D3D3"
    logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/unl-statistics/stat349
        text: "GitHub organization"

    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - section: "Course information"
        contents:
          - href: course-overview.qmd
            text: Overview
          - href: syllabus.qmd
            text: Syllabus
          - href: course-support.qmd
            text: Support
          - href: index.qmd
            text: Schedule
          - href: course-links.qmd
            text: Useful links
      - section: "Weekly materials"
        contents:
          - href: weeks/week-01.qmd
            text: "Week 1 - Getting Started"
          - href: weeks/week-02.qmd
            text: "Week 2 - Resumes"
          - href: weeks/week-03.qmd
            text: "Week 3 - References"
          - href: weeks/week-04.qmd
            text: "Week 4 - Organization"
          - href: weeks/week-05.qmd
            text: "Week 5 - Arguments"
          - href: weeks/week-06.qmd
            text: "Week 6 - Problems & Data"
          - href: weeks/week-07.qmd
            text: "Week 7 - Methods"
          - href: weeks/week-08.qmd
            text: "Week 8 - Graphics"
          - href: weeks/week-09.qmd
            text: "Week 9 - Results"
          - href: weeks/week-10.qmd
            text: "Week 10 - Intro & Conclusions"
          - href: weeks/week-11.qmd
            text: "Week 11 - Summaries"
          - href: weeks/week-12.qmd
            text: "Week 12 - Fallacies"
          - href: weeks/week-13.qmd
            text: "Week 13 - Reports"
          - href: weeks/week-14.qmd
            text: "Week 14 - Editing"
          - href: weeks/week-15.qmd
            text: "Week 15 - Presentations"

format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    mainfont: "Atkinson Hyperlegible"
    toc: true

freeze: auto

