---
title: EVALUATION OF THE 1954 POLIOMYELITIS VACCINE FIELD TRIAL
subtitle: FURTHER STUDIES OF RESULTS DETERMINING THE EFFECTIVENESS OF POLIOMYELITIS VACCINE (SALK) IN PREVENTING PARALYTIC POLIOMYELITIS
author: Thomas Francis Jr., M.D.
---

```{=html}
<style>
.design {background-color: #99ff2222}
.setting {background-color: #ff000022}
.sampling {background-color: #0000ff22}
.variables {background-color: #ff00ff22}
.statistics {background-color: #ffff0022}
</style>
```



::: aside

Annotation Key

- [Study design and data collection]{.design}

- [Setting - location, timeframe, recruitment/inclusion criteria]{.setting}

- [Sampling method]{.sampling}

- [Variables collected (and any derived variables)]{.variables}

- [Statistical analysis methods]{.statistics}

:::



The purpose of the poliomyelitis vaccine evaluation program in the field trial of 1954 was to seek a measure
of the prophylactic effect of the preparations of vaccine to be used, the only assumptions 'being that the experimental background was sound and that the vaccine was to be antigenic and noninfectious. The undertaking meant the acceptance of a public and scientific trust to provide, so far as possible, an objective analysis and unprejudiced appraisal of data obtained from numerous study areas. It must be fully realized that the evaluation program was not a tightly knit operation carried on by a single group of investigators. Rather, it was a wide-spread series of investigations that the vaccine evaluation center at the University of Michigan sought to integrate by obtaining uniform acceptance of instructions and procedures and, thus, to maintain uniformity of understanding and performance and completeness and ac- curacy of investigation and report. In effect, then, the center served as the executive agency for a study dependent upon the willingness, interest, and cooperation of the local medical profession, both administrative and practicing, and of their affiliated personnel. But, in addition, there was the extended network of virus  laboratories, geographically distributed, to aid in the specific diagnosis of reported cases; a large number of specially oriented physical therapists who would make detailed examinations of the muscular status of each patient in assigned study areas. Beyond this was the great background of public interest leading to their voluntary participation in an investigation that was, in the end, completely dependent upon their support^[Francis, T., Jr., and others: Evaluation of the 1954 Field Trials of Poliomyelitis Vaccine: Summary Report, Am. J. Pub. Health 45:1-63 (May, pt. 2) 1955.].

All data from all areas were transmitted to the center on forms devised for the specific step. Throughout the study period the major effort of the staff of the center was concentrated on getting the necessary information from the different agencies responsible for the actual work at the local level. All possible means were used to eliminate delays, inaccuracies, or omissions in the requisite reports, with the result that a high degree of completeness was finally attained.



# STUDY PLANS
The evaluation program embraced two distinct plans. [The plan originally announced by the National Foundation for Infantile Paralysis was to vaccinate all children in the second grade of school whose parents requested it, while all the children of the first and third grades were to be kept under observation as controls for the vaccinated children. The ease of carrying out vaccination under such conditions recommends the procedure, but it presents possible disadvantages in the evaluation by the ready opportunity for the introduction of bias at any stage in the diagnosis and investigation of cases. The vaccinated persons are those who specifically volunteer; the controls comprise both those who might volunteer and those who would not. The age groups do not correspond, although the first and third grades bridge the second grade in this respect. It can readily be determined whether a child was vaccinated or not, and that knowledge could influence subsequent consideration. ]{.design}

@tbl-1 presents the number of participants in the "observed study areas."

| Study Population                  | No.      | % of 2nd Grade | % of Total Population  |
|-----------------------------------|----------|----------------|------------------------|
| **All grades**                    |          |                |                        |
|  - Total                             | 1,080,680|                | 100.0                  |
|  - Requests                          | 567,210  |                | 52.5                   |
| **2nd grade (requests)**          |          |                |                        |
|  - Requests                          | 245,895  | 69.2           | 22.8                   |
|  - Complete vaccinations             | 221,998  | 62.4           | 20.5                   |
|  - Incomplete vaccinations           | 9,904    | 2.8            | 0.9                    |
|  - Absent or withdrew                | 13,993   | 3.9            | 1.3                    |
| **1st and 3rd grades (requests)** | 321,315  |                | 29.7                   |
| **All grades**                    |          |                |                        |
|  - Participation not requested       | 332,870  |                | 30.8                   |
|  - Participation not recorded        | 180,600  |                | 16.7                   |

: Distribution of Study Population, by Participation Status and Vaccination Status, Observed Areas 
{#tbl-1}

In order to achieve strict impartiality in the study of patients in test and control groups, the second plan of study was introduced. [It comprised all children of the first, second, and third grades whose parents requested their participation, with a clear understanding that half would receive vaccine and the other half a placebo, while knowledge of the inoculum was available only by a code held at the evaluation center.]{.design} Those who received the placebo were the controls and have been shown in all respects to be counterparts of the vaccinated children (table 2). [Those who did not participate were not considered additional controls. The uninoculated persons were, however, to be followed in the same manner as the participants; it was also to be true of uninoculated persons in the second grade of observed areas. This was adopted to gain uniformity of investigative procedure without consideration of vaccination status and to avoid selective problems at the local level. But it should be emphasized that those not included as participants are not an integral part of the evaluation; they are a different population. Evidence that they are different was clearly supplied in a survey of the socioeconomic status and the reaction to health problems among families of the placebo study areas.]{.sampling} Numerous studies have indicated differences in antibody development and susceptibility to poliomyelitis between portions of populations of different socioeconomic levels, and the differences demonstrated in the survey indicated that the nonrequesting population might well be a more resistant group than the inoculated.


# DATA REQUIRED FOR EVALUATION

[The vaccination program was carried out between the end of April and mid-June.]{.setting} [The first problem was that of collecting and verifying the basic information on each of the 1,829,996 children in the total study population. It included a record of the lot of material given in each inoculation to each child. These data were transferred to punched cards so that tables describing the population according to essential characteristics could be prepared. It was an extensive but essential task, since it provided the necessary identification of the vaccinated and control persons in whom the incidence of poliomyelitis would be investigated and the measurement of vaccine's effect would be made. In addition, from more than 40,000 children of the vaccinated and control groups samples of serum were obtained prior to the time of injection, together with serums taken two weeks after the clinics were completed and again five months later, and were to be tested in the respective laboratories. These records were also established and results received at the center. From them the distribution of antibody in this segment of the population in different parts of the country, the response to vaccine, the persistence of effect, and possibly information on the extent of natural exposure to poliomyelitis virus in the different areas during the study period as indicated by antibody changes could be determined.]{.variables}


| Study Population                           | No.     | %     |
|--------------------------------------------|---------|-------|
| **Total in grades 1, 2, and 3**            | 749,236 | 100.0 |
| **Total requests to participate**          | 455,474 | 60.8  |
| Complete series of injections  |         |       |
|  - Vaccine            | 200,745 | 26.8  |
|  - Placebo            | 201,229 | 26.9  |
| Incomplete injections          |         |       |
|  - Vaccine            | 8,484   | 1.1   |
|  - Placebo            | 8,577   | 1.1   |
| **Absent at first clinic or withdrew**     | 36,439  | 4.9   |
| **Number not requesting participation**    | 280,868 | 37.5  |
| **Participation status not recorded**      | 12,894  | 1.7   |

: Distribution of Study Population, by Participation Status and Vaccination Status - Placebo Areas {#tbl-2}

[The second phase in the evaluation was concerned with discovery and identification of all cases of poliomyelitis or suspected poliomyelitis in all children of the first, second, and third grades in the study areas. The various steps in the investigation of a case are: (1) physician's diagnosis—report to local health department; (2) telegraphic report to vaccine evaluation center; (3) action of local health department, including (a) clinicoepidemiological investigation and report to vaccine evaluation center, form FT-6, (b) collection and shipment of laboratory specimens (or by laboratory) and notice to vaccine evaluation center, form FT-9, and (c) notification of physical therapist; (4) first muscle evaluation by physical therapist (10 to 20 days) and physician's interpretation of patient's status, form FT-7; (5) collection of convalescent serum for laboratory, form FT-9; (6) second muscle evaluation by physical therapist (50 to 70 days) and physician's interpretation of patient's entire illness, form FT-8; (7) report of virus isolation, tests of antibody titer, laboratory diagnosis, form FT-10; (8) establishment and application of criteria for diagnosis of individual patient; and (9) integration of all data into final vaccine evaluation center diagnosis. The criteria for diagnosis of poliomyelitis, for designation of a case as paralytic and its severity, and for the interpretation of laboratory results were carefully drawn.]{.variables} In this we had the continued help of an advisory committee comprised of expert clinicians, virologists, biostatisticians, epidemiologists, and administrators. The information concerning each case was carefully reviewed and the diagnostic classification made without knowledge of its vaccination status so that objectivity was readily maintained. Inevitably, difficulties in decision were encountered when results from different pieces of data were not in agreement, but the effort was made to follow a consistent plan of interpretation.

# RESULTS

[The study period was defined as the period from two weeks after the time of the third injections in an area to Dec. 31, 1954. The beginning was selected because it coincided generally with the time when second blood specimens were obtained for measurement of antigenic response to vaccine.]{.setting} During the study period there were 1,013 cases reported to be poliomyelitis or suspected poliomyelitis; 428 in the total study population of placebo areas and 585 in the total study population of observed areas. With the criteria employed, 67.6% were classified as paralytic, 17.6% as nonparalytic, and 14.8% as not poliomyelitis or doubtful. There was no major difference in distribution of diagnoses in the two populations.

Table 3 shows the cases distributed according to the various segments of the total populations involved. It must be emphasized again that the evaluation is limited to a comparison of incidence in the vaccinated and in the established controls. The nonparticipating portions of the populations, that is, those who specifically refused to participate, are not additional controls. That decision was firmly established well in advance of the tabulation of results. The data are presented only because they are available and for completeness of reporting. The cases and rates per 100,000 of specific population are listed. In the placebo control areas there was a total of 82 cases reported among the 200,745 vaccinated and 162 among the 201,229 who received a placebo. The corresponding rates are 41 and 81—a ratio of 1:2; however, 25 and 20 cases, respectively, were classified as not poliomyelitis or doubtful. Thus, when the cases accepted as poliomyelitis are compared, there are 57 and 142, respectively, with rates of 28 and 71, a ratio of 1:2.5. When these are subdivided into paralytic and nonparalytic groups, no difference is observed between the incidence of nonparalytic cases among vaccinated and control persons. The sole significant difference, then, resides in the cases classified as paralytic poliomyelitis; there were 33 in the vaccinated group and 3.5 times as many, 115, in the placebo control group. In the observed control study, the number of controls is 3.3 times that of the inoculated; hence, for comparison the rates must be used. Here, again, there is no significant difference between the rates in nonparalytic cases or between the doubtful and not poliomyelitis groups in the vaccinated and control patients. The rates for paralytic cases are, however, 17 and 46 respectively — a ratio of 1:2.7. This possibility was an essential reason for establishing the strictly controlled placebo study. Moreover, the uninoculated — or refused — portion of the second grade in observed areas also had a lower rate than the designated controls who themselves were both "yes" and "no" participants. When the incidence rates in control and uninoculated groups combined are calculated for the placebo study and for the observed study, they are the same, 43.7 and 43.9 respectively. The differences disappear.


| Study Group                | Subgroup | Study Population | All Reported Cases (No) | All Reported Cases (Rate) | Poliomyelitis Total (No) | Poliomyelitis Total (Rate) | Poliomyelitis Paralytic (No) | Poliomyelitis Paralytic (Rate) | Poliomyelitis Nonparalytic (No) | Poliomyelitis Nonparalytic (Rate) | Doubtful Or Not Poliomyelitis (No) | Doubtful Or Not Poliomyelitis (Rate) |
|---------------------------|----------------:|---------------------:|-----------------------:|------------------------:|--------------------------:|-----------------------------:|-------------------------------:|-------------------------------:|--------------------------------:|-------------------------------:|---------------------------------:|
| All areas          | total |  1,829,916       | 1,013               | 55                    | 863                    | 47                       | 685                         | 37                            | 178                           | 10                             | 150                           | 8                                |
| Placebo areas |  total      | 749,236         | 428                 | 57                    | 358                    | 48                       | 270                         | 36                            | 88                            | 12                             | 70                            | 9                                |
| Placebo areas |  Vaccinated              | 200,745         | 82                  | 41                    | 57                     | 28                       | 33                          | 16                            | 24                            | 12                             | 25                            | 12                               |
| Placebo areas |  Placebo                 | 201,229         | 162                 | 81                    | 142                    | 71                       | 115                         | 57                            | 27                            | 13                             | 20                            | 10                               |
| Placebo areas | Not inoculated^[Includes 8577 children who received one or two injections of placebo.]        | 338,778         | 182                 | 54                    | 157                    | 46                       | 121                         | 36                            | 36                            | 11                             | 25                            | 7                                |
| Placebo areas | Incomplete vaccinations | 8,484           | 2                   | 24                    | 2                      | 24                       | 1                           | 12                            | 1                             | 12                             | —                             | —                                |
| Observed areas | total     | 1,080,680       | 585                 | 54                    | 505                    | 47                       | 415                         | 38                            | 90                            | 8                              | 80                            | 7                                |
| Observed areas | Vaccinated              | 221,998         | 76                  | 34                    | 56                     | 25                       | 38                          | 17                            | 18                            | 8                              | 20                            | 9                                |
| Observed areas | Controls ^[1st and 3rd grade total population]              | 725,173         | 439                 | 61                    | 391                    | 54                       | 330                         | 46                            | 61                            | 8                              | 48                            | 6                                |
| Observed areas | 2nd grade not inoculated| 123,605         | 66                  | 53                    | 54                     | 44                       | 43                          | 35                            | 11                            | 9                              | 12                            | 10                               |
| Observed areas | Incomplete vaccinations | 9,904           | 4                   | 40                    | 4                      | 40                       | 4                           | 40                            | —                             | —                              | —                             | —                                |

: Summary of Study Cases by  Diagnostic Class and Vaccination Status, Rate per 100,000 {#tbl-3}


| Group              | Subgroup                      | Total | Virus Type 1 Recovered | Virus Type 2 Recovered | Virus Type 3 Recovered | Negative Isolation | Other Virus Recovered | Not Collected Or Not Done | Week 0 | Week 1 | Week 2 | Week 3 | Week 4 | Week 5 | Week 6 | Week 7 | Week 8 | Week 9 |
|--------------------|-------------------------------|-------|----------------------|----------------------|----------------------|-------------------|---------------------|------------------------|-------|-------|-------|-------|-------|-------|-------|-------|-------|-------|
| Vaccinates         | Paralytic                     | 2     |                      |                      |                      | 2                 |                     |                        |       |       |       |       |       |       | 1     |       | 1     |       |
| Vaccinates         | Nonparalytic                  | 1     |                      |                      |                      |                   | 1                   |                        |       |       |       |       |       |       |       | 1     |       |       |
| Vaccinates         | Not poliomyelitis or doubtful | 3     |                      |                      |                      | 1                 |                     | 2                      |       |       |       |       |       |       | 1     | 1     |       | 1     |
| Placebo            | Paralytic                     | 4     |                      |                      | 2                    | 2                 |                     |                        |       |       |       |       |       | 1     | 1     |       | 2     |       |
| Placebo            | Nonparalytic                  |       |                      |                      |                      |                   |                     |                        |       |       |       |       |       |       |       |       |       |       |
| Placebo            | Not poliomyelitis or doubtful | 3^[Partial placebo, one case]    |                      |                      |                      | 1                 |                     | 2                      |       |       |       | 1     |       | 1     |       |       | 1     |       |
| Partial vaccinates | Paralytic                     | 2     | 1                    |                      |                      | 1                 |                     |                        |       |       | 1     |       | 1^[Doubtful facial]    |       |       |       |       |       |
| Partial vaccinates | Nonparalytic                  |       |                      |                      |                      |                   |                     |                        |       |       |       |       |       |       |       |       |       |       |
| Partial vaccinates | Not poliomyelitis or doubtful |       |                      |                      |                      |                   |                     |                        |       |       |       |       |       |       |       |       |       |       |
| All other          | Paralytic                     | 8     | 1                    |                      | 2                    | 1                 |                     | 4                      |       |       | 1     | 1     |       | 1     |       | 1     | 3     | 1     |
| All other          | Nonparalytic                  | 4     |                      |                      | 1                    | 3                 |                     |                        |       |       |       |       |       |       |       | 1     | 2     | 1     |
| All other          | Not poliomyelitis or doubtful | 5     |                      |                      |                      | 5                 |                     |                        |       |       |       |       |       |       |       | 4     | 1     |       |


: Study Cases with Onset up to Nine Weeks from Date of first Inoculation, by Vaccination Status ^[Date of first inoculation in school used for uninoculated children.] - Placebo Areas {#tbl-4}


*Lack of Evidence of Provocation or Infection from Vaccination.* — It had been suggested that the placebo inoculations might exert some provocative influence toward paralytic poliomyelitis. Analysis of the data reveals no evidence of exaggerated incidence or localization of paralysis associated with inoculations. Further information is presented regarding the occurrence of poliomyelitis in the total study populations during the nine-week period from the beginning of vaccination to four weeks after the third injections in an area. There were 129 reported cases. As seen in tables 4 and 5, no distinctive difference in incidence in time of occurrence of cases appears in the vaccinated, placebo, or uninoculated groups of the placebo areas, or in the corresponding groups of the observed areas. The latter included many more southern states where poliomyelitis was already being reported at the time of vaccination, especially in Texas where half of the cases occurred (table 6). The number of cases in the first and third grade controls and in the vaccinated group is directly proportionate to the population. The tables also contain the results of efforts to isolate virus from the reported cases. From the four cases of paralytic poliomyelitis among those receiving vaccine, partial or complete series, type 1 virus was recovered once; the others were negative. Poliomyelitis virus was recovered only once from vaccinated persons in the observed areas, a type 2. From half of the paralytic cases in the control group in which tests were done, poliomyelitis virus was isolated: eight type 1 and four type 3. There were only two instances of poliomyelitis in associates of vaccinated persons during this nine-week period. The study member in New York state received the third injection of vaccine on June 17; the' sibling developed nonparalytic poliomyelitis 26 days later, and 2 days later the vaccinated child developed poliomyelitis with minimal paralytic signs; no virus was recovered. In Texas, a child received his third injection of vaccine on June 15, and 21 days later had the onset of mild bulbar poliomyelitis, but no virus was recovered. The sibling had his onset on the same day, with nonparalytic polio myelitis and negative virus studies. There were three instances of similar nature in the placebo group, three in the uninoculated of the placebo study areas, three in the controls, and one in the nonparticipating group of observed areas. There is, therefore, no indication of undue transmission of poliomyelitis virus from vaccinated persons in this period to other members of the household.


| Group              | Subgroup                      | Total | Virus Type 1 | Virus Type 2 | Virus Type 3 | Negative Isolation | Other Virus Recovered | Not Collected Or Not Done | Week 0 | Week 1 | Week 2 | Week 3 | Week 4 | Week 5 | Week 6 | Week 7 | Week 8 | Week 9 |
|--------------------|-------------------------------|-------|----------------------|----------------------|----------------------|-------------------|---------------------|------------------------|-------|-------|-------|-------|-------|-------|-------|-------|-------|-------|
| Vaccinates         | Paralytic                     | 7     |                      |                      |                      | 6                 |                     | 1                      |       | 1     |       | 1     |       |       | 1     | 1     | 3     |       |
| Vaccinates         | Nonparalytic                  | 5     |                      | 1                    |                      | 3                 | 1                   |                        |       |       | 1     |       | 1     | 1     | 1     |       | 1     |       |
| Vaccinates         | Not poliomyelitis or doubtful | 6     |                      |                      |                      | 4                 |                     | 2                      |       |       |       | 2     |       |       | 1     | 2     | 1     |       |
| Control            | Paralytic                     | 35    | 8                    |                      | 4                    | 12                |                     | 11                     | 3     | 3     | 4     | 2     | 4     | 3     | 6     | 1     | 5     | 4     |
| Control            | Nonparalytic                  | 15    |                      |                      | 1                    | 4                 |                     | 10                     | 2     | 1     |       |       | 4     | 1     | 2     | 2     | 3     |       |
| Control            | Not poliomyelitis or doubtful | 9     |                      |                      |                      | 8                 |                     | 1                      | 1     | 2     |       | 1     | 1     |       |       | 1     | 2     | 1     |
| Partial vaccinates | Paralytic                     | 4     |                      |                      |                      | 3                 |                     | 1                      |       | 1     |       | 1     |       | 2     |       |       |       |       |
| Partial vaccinates | Nonparalytic                  |       |                      |                      |                      |                   |                     |                        |       |       |       |       |       |       |       |       |       |       |
| Partial vaccinates | Not poliomyelitis or doubtful | 4     |                      |                      |                      | 4                 |                     |                        |       | 1     | 1     |       | 1     | 1     |       |       |       |       |
| All other          | Paralytic                     | 5     | 1                    |                      | 1                    | 2                 |                     |                        |       |       | 1     | 1     |       |       |       | 3     |       |       |
| All other          | Nonparalytic                  | 5     |                      |                      |                      | 2                 |                     | 3                      | 1     | 1     |       | 1     | 1     | 1     |       | 1     |       |       |
| All other          | Not poliomyelitis or doubtful | 2     |                      |                      |                      | 2                 |                     |                        |       |       |       |       |       |       | 1     |       |       |       |

: Study Cases with Onset up to Nine Weeks from Date of First Inoculation, by Vaccination Status^[Date of first inoculation in school used for uninoculated children.] — Observed Areas {#tbl-5}




| Group              | Subgroup                      | Total | Virus Type 1 | Virus Type 2 | Virus Type 3 | Negative Isolation | Not Collected Or Not Done | Week 0 | Week 1 | Week 2 | Week 3 | Week 4 | Week 5 | Week 6 | Week 7 | Week 8 | Week 9 |
|--------------------|-------------------------------|-------|----------------------|----------------------|----------------------|-------------------|---------------------|------------------------|-------|-------|-------|-------|-------|-------|-------|-------|-------|-------|
| Vaccinates         | Paralytic                     | 5     |                      |                      |                      | 5                 |                     | 1                      |       | 1     |       |       |       |       |       | 1     | 3     |       |
| Vaccinates         | Nonparalytic                  | 3     |                      |                      |                      | 3                 |                     |                        |       |       | 1     |       | 1     |       | 1     |       | 1     |       |
| Vaccinates         | Not poliomyelitis or doubtful | 2     |                      |                      |                      | 2                 |                     |                        |       |       |       | 1     |       |       |       | 1     |       |       |
| Control            | Paralytic                     | 16    | 5                    |                      | 2                    | 6                 |                     | 3                      |       | 1     |       | 2     | 2     | 2     | 4     | 1     | 2     | 2     |
| Control            | Nonparalytic                  | 10    |                      |                      |                      | 2                 |                     | 8                      | 2     | 1     |       |       | 1     | 1     | 2     | 1     | 3     |       |
| Control            | Not poliomyelitis or doubtful | 4     |                      |                      |                      | 3                 |                     | 1                      | 1     | 1     |       |       | 1     |       |       |       |       | 1     |
| Partial vaccinates | Paralytic                     |       |                      |                      |                      |                   |                     |                        |       |       |       |       |       |       |       |       |       |       |
| Partial vaccinates | Nonparalytic                  |       |                      |                      |                      |                   |                     |                        |       |       |       |       |       |       |       |       |       |       |
| Partial vaccinates | Not poliomyelitis or doubtful | 1     |                      |                      |                      | 1                 |                     |                        |       |       |       | 1     |       |       |       |       |       |       |
| All other          | Paralytic                     | 1     | 1                    |                      |                      | 2                 |                     |                        |       |       |       |       |       |       | 1     |       |       |       |
| All other          | Nonparalytic                  | 2     |                      |                      |                      | 2                 |                     |                        |       |       |       |       | 1     | 1     |       |       |       |       |
| All other          | Not poliomyelitis or doubtful | 2     |                      |                      |                      | 2                 |                     |                        |       |       |       | 1     |       |       |       |       |       |       |

: Study Cases with Onset up to Nine Weeks from Date of First Inoculation, by Vaccination Status^[Date of first inoculation in school used for uninoculated children. No viruses other than the poliomyelitis virus were recovered. ] - Texas {#tbl-6}

*Distribution of Paralytic and Laboratory Confirmed Cases.* - The subsequent analyses of case distribution were directed toward the combining of clinical and laboratory data that enhance the reliability of diagnosis. A summary of these progessive stages with accompanying estimates of effectiveness in the two types of study are given in table 7. In the placebo areas there was a distinct trend for the differences in ratio between vaccinated and controls to increase as the severity of paralytic involvement increased. In spinal paralytic cases of minimal degrees of involvement the difference was only 2:1, suggesting that here, too, cases that were not specific poliomyelitis virus infections were included in these clinical classifications. In the more severe classes, how¬
ever, the distinction became quite marked, emphasizing the possibility that the vaccine exhibited its major influence in preventing significant muscular impairment. The difference in rates for bulbospinal cases was pronounced and highly significant.

The same trend occurs among spinal paralytic cases in observed areas, but the difference between total bulbospinal rates is less, apparently owing to the lack of effect in cases with minimal paralytic ratings. The limited number of cases, however, can significantly limit the degree of numerical agreement in the two studies. Analysis of paralytic cases that were designated by virus isolation, serology, or virus in family associates as specific infections with the known types of poliomyelitis virus was then undertaken. This obviously reduces again the number of cases admitted to consideration. It is seen, however, that with these criteria, the estimated effect of vaccine was the same in spinal paralytic cases of both placebo and observed study areas. However, the discrepancy between the bulbospinal cases in the two studies persists.


| Diagnostic Classification      | Placebo, Vaccinated, No Cases | Placebo, Controls , No Cases| Placebo Significance Level | Placebo, % Effectiveness Estimate | Placebo, %Effectiveness Lower Limit | Observed, Vaccinated, No Cases | Observed, Controls, No Cases | Observed, Significance Level | Observed, %Effectiveness Estimate | Observed, % Effectiveness Lower Limit | Source Of Data |
|------------------------------|-----------------------------|----------------------------|-----------------------------|----------------------------------|-----------------------------------|-------------------------------|------------------------------|-------------------------------|------------------------------------|-------------------------------------|--------------|
| Total cases reported ^[Because of small numbers the bulbar and fatal cases are omitted. All fatal cases occurred in controls.]       | 82                          | 162                        | <0.001                      | 49                               | 36                                | 76                            | 439                          | <0.001                        | 44                                 | 32                                  | Table 3      |
| Total poliomyelitis          | 57                          | 142                        | <0.001                      | 60                               | 49                                | 56                            | 391                          | <0.001                        | 54                                 | 32                                  |              |
| All paralytic                | 33                          | 115                        | <0.001                      | 72                               | 61                                | 38                            | 330                          | <0.001                        | 62                                 | 51                                  |              |
| All nonparalytic^[Nonparalytic case distribution difference not significant at any stage of analysis.]           | 24                          | 27                         | NS                          |                                  |                                   | 18                            | 61                           | NS                            |                                    |                                     |              |
| Paralytic-spinal             | 28                          | 70                         | <0.001                      | 60                               | 39                                | 20                            | 199                          | <0.001                        | 66                                 | 53                                  | Tables 3a, b^[Francis, T., Jr., and others: Evaluation of the 1954 Field Trials of Poliomyelitis Vaccine: Summary Report, Am. J. Pub. Health 45:1-63 (May, pt. 2) 1955.] |
| Bulbospinal                  | 2                           | 36                         | <0.001                      | 94                               | 81                                | 15                            | 100                          | <0.001                        | 50                                 | 19                                  |              |
| Laboratory confirmed         |                             |                            |                             |                                  |                                   |                               |                              |                               |                                    |                                     |              |
| Spinal                       | 8                           | 45                         | <0.001                      | 82                               | 65                                | 7                             | 127                          | <0.001                        | 83                                 | 64                                  | Tables 5a, b‡ |
| Bulbospinal                  | 2                           | 23                         | <0.001                      | 91                               | 68                                | 9                             | 71                           | <0.01                         | 60                                 | 23                                  |              |
| All virus positive           |                             |                            |                             |                                  |                                   |                               |                              |                               |                                    |                                     |              |
| Total                        | 15                          | 70                         | <0.001                      | 80                               | 65                                | 20                            | 210                          | <0.001                        | 69                                 | 36                                  | Tables 6a, b‡ |
| Type 1                       | 13                          | 39                         | <0.001                      | 68                               | 41                                | 14                            | 114                          | <0.001                        | 62                                 | 33                                  |              |
| Type 2                       | 0                           | 6                          | <0.05                       | 100                              | 33                                | 2                             | 34                           | <0.01                         | 80                                 | 33                                  |              |
| Type 3                       | 2                           | 25                         | <0.001                      | 92                               | 72                                | 4                             | 62                           | <0.001                        | 78                                 | 47                                  |              |

: Estimates of Effectiveness of Vaccine at Successive Stages of Analysis {#tbl-7}


Finally, the distribution was studied of all cases, paralytic and nonparalytic, from whom a specific poliomyelitis virus was isolated. In placebo areas an effectiveness of 68% was estimated against type 1, and 90% or more against types 2 and 3. In observed areas the trend was the same but lower. What, then, can be given as the effectiveness of vaccine? The calculations pre
sented in the table appear to be valid estimates from the summarized data. Subsequent review has not revealed significant error. It is fully recognized that larger numbers would have created greater security, but the data obtained are unprejudiced appraisals. The strictly controlled placebo study provides the data in which there is greater confidence than those from the observed control study. In fact, the results from the observed areas would be more difficult to interpret if they had not followed the trend of those obtained in the placebo study. The lesser effect seen against type 1 virus is in accord with the lesser antigenic effect of a number of the preparations of vaccine measured against type 1 virus. But taking the composite results against laboratory confirmed cases of paralytic poliomyelitis an effectiveness of 80 to 90% was observed in the placebo study areas and 60 to 80% in observed study areas. It must be emphasized that the results presented apply to the circumstances in effect for the 1954 studies during which intensive efforts were made to obtain as complete and uniform data as conditions of study would permit.

There are questions arising from the data to which there is yet no ready answer. The incidence of paralytic cases in the 6-year-old group did not appear significantly different in vaccinated and controls of the placebo areas. It can only be pointed out at the present that when these cases were considered in terms of virus isolation, there were four cases of type 1 in each group, but there were no type 2 or type 3 cases in the vaccinated while one and five cases, respectively, occurred in the controls. Study of
this problem is continuing.

# SUMMARY

This review has been directed to a further summary of the report of the evaluation of the 1954 field trial of poliomyelitis vaccine. The data appear on further examination to retain their validity. Possible harmful effects of the poliomyelitis vaccine were not indicated by the data. Again, the definition of controls and the value of strictly controlled studies is emphasized. It is apparent that the medical profession at large needs further preparation for effective participation in the investigation of health problems in which their activities as physicians contribute the essential data.


# End Notes

- From the Department of Epidemiology and the Virus Laboratory, School of Public Health, and the Vaccine Evaluation Center, University of Michigan.

- Read in the Panel Discussion on Prospects for the Control of Poliomyelitis before the Joint Meeting of the Section on Pediatrics and the Section on Preventive and Industrial Medicine and Public Health at the 104th Annual Meeting of the American Medical Association, Atlantic City, June 7, 1955.

- This study was aided by a grant from the National Foundation for Infantile Paralysis, Inc.
