<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Thomas Francis Jr., M.D.">

<title>EVALUATION OF THE 1954 POLIOMYELITIS VACCINE FIELD TRIAL – STAT 349 - Spring 2025</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-4d9afe2b8d18ee9fa5d0d57b5ed4214d.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-d7964e062797f14afdac39f13a0a6f7e.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark-6a19d919a1cfc19ed6f13e45053f1323.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../../site_libs/bootstrap/bootstrap-d7964e062797f14afdac39f13a0a6f7e.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<meta property="og:title" content="EVALUATION OF THE 1954 POLIOMYELITIS VACCINE FIELD TRIAL – STAT 349 - Spring 2025">
<meta property="og:description" content="FURTHER STUDIES OF RESULTS DETERMINING THE EFFECTIVENESS OF POLIOMYELITIS VACCINE (SALK) IN PREVENTING PARALYTIC POLIOMYELITIS">
<meta property="og:site_name" content="STAT 349 - Spring 2025">
<meta name="twitter:title" content="EVALUATION OF THE 1954 POLIOMYELITIS VACCINE FIELD TRIAL – STAT 349 - Spring 2025">
<meta name="twitter:description" content="FURTHER STUDIES OF RESULTS DETERMINING THE EFFECTIVENESS OF POLIOMYELITIS VACCINE (SALK) IN PREVENTING PARALYTIC POLIOMYELITIS">
<meta name="twitter:image" content="https://unl-statistics.github.io/stat349/instructions/methods-papers/images/twitter-card.png">
<meta name="twitter:creator" content="@srvanderplas">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-sidebar docked slimcontent quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">EVALUATION OF THE 1954 POLIOMYELITIS VACCINE FIELD TRIAL</li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-center sidebar-header">
      <a href="../../index.html" class="sidebar-logo-link">
      <img src="../../images/logo.png" alt="" class="sidebar-logo light-content py-0 d-lg-inline d-none">
      <img src="../../images/logo.png" alt="" class="sidebar-logo dark-content py-0 d-lg-inline d-none">
      </a>
      <div class="sidebar-tools-main">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Course information</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../course-overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Overview</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../syllabus.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Syllabus</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../course-support.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Support</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Schedule</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../course-links.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Useful links</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Weekly materials</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../weeks/week-01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 1 - Getting Started</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../weeks/week-02.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 2 - Resumes</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../weeks/week-03.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 3 - References</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../weeks/week-04.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 4 - Organization</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../weeks/week-05.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 5 - Arguments</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../weeks/week-06.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 6 - Problems &amp; Data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../weeks/week-07.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 7 - Methods</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../weeks/week-08.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 8 - Graphics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../weeks/week-09.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 9 - Results</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../weeks/week-10.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 10 - Intro &amp; Conclusions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../weeks/week-11.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 11 - Summaries</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../weeks/week-12.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 12 - Fallacies</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../weeks/week-13.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 13 - Reports</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../weeks/week-14.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 14 - Editing</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../weeks/week-15.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 15 - Presentations</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#study-plans" id="toc-study-plans" class="nav-link active" data-scroll-target="#study-plans">STUDY PLANS</a></li>
  <li><a href="#data-required-for-evaluation" id="toc-data-required-for-evaluation" class="nav-link" data-scroll-target="#data-required-for-evaluation">DATA REQUIRED FOR EVALUATION</a></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">RESULTS</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary">SUMMARY</a></li>
  <li><a href="#end-notes" id="toc-end-notes" class="nav-link" data-scroll-target="#end-notes">End Notes</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/unl-statistics/stat349/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content page-columns page-full column-body" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">EVALUATION OF THE 1954 POLIOMYELITIS VACCINE FIELD TRIAL</h1>
<p class="subtitle lead">FURTHER STUDIES OF RESULTS DETERMINING THE EFFECTIVENESS OF POLIOMYELITIS VACCINE (SALK) IN PREVENTING PARALYTIC POLIOMYELITIS</p>
</div>



<div class="quarto-title-meta column-body">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Thomas Francis Jr., M.D. </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<style>
.design {background-color: #99ff2222}
.setting {background-color: #ff000022}
.sampling {background-color: #0000ff22}
.variables {background-color: #ff00ff22}
.statistics {background-color: #ffff0022}
</style>

<div class="no-row-height column-margin column-container"><div class="margin-aside">
<p>Annotation Key</p>
<ul>
<li><p><span class="design">Study design and data collection</span></p></li>
<li><p><span class="setting">Setting - location, timeframe, recruitment/inclusion criteria</span></p></li>
<li><p><span class="sampling">Sampling method</span></p></li>
<li><p><span class="variables">Variables collected (and any derived variables)</span></p></li>
<li><p><span class="statistics">Statistical analysis methods</span></p></li>
</ul>
</div></div><p>The purpose of the poliomyelitis vaccine evaluation program in the field trial of 1954 was to seek a measure of the prophylactic effect of the preparations of vaccine to be used, the only assumptions ’being that the experimental background was sound and that the vaccine was to be antigenic and noninfectious. The undertaking meant the acceptance of a public and scientific trust to provide, so far as possible, an objective analysis and unprejudiced appraisal of data obtained from numerous study areas. It must be fully realized that the evaluation program was not a tightly knit operation carried on by a single group of investigators. Rather, it was a wide-spread series of investigations that the vaccine evaluation center at the University of Michigan sought to integrate by obtaining uniform acceptance of instructions and procedures and, thus, to maintain uniformity of understanding and performance and completeness and ac- curacy of investigation and report. In effect, then, the center served as the executive agency for a study dependent upon the willingness, interest, and cooperation of the local medical profession, both administrative and practicing, and of their affiliated personnel. But, in addition, there was the extended network of virus laboratories, geographically distributed, to aid in the specific diagnosis of reported cases; a large number of specially oriented physical therapists who would make detailed examinations of the muscular status of each patient in assigned study areas. Beyond this was the great background of public interest leading to their voluntary participation in an investigation that was, in the end, completely dependent upon their support<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>.</p>
<p>All data from all areas were transmitted to the center on forms devised for the specific step. Throughout the study period the major effort of the staff of the center was concentrated on getting the necessary information from the different agencies responsible for the actual work at the local level. All possible means were used to eliminate delays, inaccuracies, or omissions in the requisite reports, with the result that a high degree of completeness was finally attained.</p>
<section id="study-plans" class="level1">
<h1>STUDY PLANS</h1>
<p>The evaluation program embraced two distinct plans. <span class="design">The plan originally announced by the National Foundation for Infantile Paralysis was to vaccinate all children in the second grade of school whose parents requested it, while all the children of the first and third grades were to be kept under observation as controls for the vaccinated children. The ease of carrying out vaccination under such conditions recommends the procedure, but it presents possible disadvantages in the evaluation by the ready opportunity for the introduction of bias at any stage in the diagnosis and investigation of cases. The vaccinated persons are those who specifically volunteer; the controls comprise both those who might volunteer and those who would not. The age groups do not correspond, although the first and third grades bridge the second grade in this respect. It can readily be determined whether a child was vaccinated or not, and that knowledge could influence subsequent consideration.</span></p>
<p><a href="#tbl-1" class="quarto-xref">Table&nbsp;1</a> presents the number of participants in the “observed study areas.”</p>
<div id="tbl-1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Distribution of Study Population, by Participation Status and Vaccination Status, Observed Areas
</figcaption>
<div aria-describedby="tbl-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 41%">
<col style="width: 11%">
<col style="width: 18%">
<col style="width: 28%">
</colgroup>
<thead>
<tr class="header">
<th>Study Population</th>
<th>No.</th>
<th>% of 2nd Grade</th>
<th>% of Total Population</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>All grades</strong></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>- Total</td>
<td>1,080,680</td>
<td></td>
<td>100.0</td>
</tr>
<tr class="odd">
<td>- Requests</td>
<td>567,210</td>
<td></td>
<td>52.5</td>
</tr>
<tr class="even">
<td><strong>2nd grade (requests)</strong></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>- Requests</td>
<td>245,895</td>
<td>69.2</td>
<td>22.8</td>
</tr>
<tr class="even">
<td>- Complete vaccinations</td>
<td>221,998</td>
<td>62.4</td>
<td>20.5</td>
</tr>
<tr class="odd">
<td>- Incomplete vaccinations</td>
<td>9,904</td>
<td>2.8</td>
<td>0.9</td>
</tr>
<tr class="even">
<td>- Absent or withdrew</td>
<td>13,993</td>
<td>3.9</td>
<td>1.3</td>
</tr>
<tr class="odd">
<td><strong>1st and 3rd grades (requests)</strong></td>
<td>321,315</td>
<td></td>
<td>29.7</td>
</tr>
<tr class="even">
<td><strong>All grades</strong></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>- Participation not requested</td>
<td>332,870</td>
<td></td>
<td>30.8</td>
</tr>
<tr class="even">
<td>- Participation not recorded</td>
<td>180,600</td>
<td></td>
<td>16.7</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>In order to achieve strict impartiality in the study of patients in test and control groups, the second plan of study was introduced. <span class="design">It comprised all children of the first, second, and third grades whose parents requested their participation, with a clear understanding that half would receive vaccine and the other half a placebo, while knowledge of the inoculum was available only by a code held at the evaluation center.</span> Those who received the placebo were the controls and have been shown in all respects to be counterparts of the vaccinated children (table 2). <span class="sampling">Those who did not participate were not considered additional controls. The uninoculated persons were, however, to be followed in the same manner as the participants; it was also to be true of uninoculated persons in the second grade of observed areas. This was adopted to gain uniformity of investigative procedure without consideration of vaccination status and to avoid selective problems at the local level. But it should be emphasized that those not included as participants are not an integral part of the evaluation; they are a different population. Evidence that they are different was clearly supplied in a survey of the socioeconomic status and the reaction to health problems among families of the placebo study areas.</span> Numerous studies have indicated differences in antibody development and susceptibility to poliomyelitis between portions of populations of different socioeconomic levels, and the differences demonstrated in the survey indicated that the nonrequesting population might well be a more resistant group than the inoculated.</p>
</section>
<section id="data-required-for-evaluation" class="level1">
<h1>DATA REQUIRED FOR EVALUATION</h1>
<p><span class="setting">The vaccination program was carried out between the end of April and mid-June.</span> <span class="variables">The first problem was that of collecting and verifying the basic information on each of the 1,829,996 children in the total study population. It included a record of the lot of material given in each inoculation to each child. These data were transferred to punched cards so that tables describing the population according to essential characteristics could be prepared. It was an extensive but essential task, since it provided the necessary identification of the vaccinated and control persons in whom the incidence of poliomyelitis would be investigated and the measurement of vaccine’s effect would be made. In addition, from more than 40,000 children of the vaccinated and control groups samples of serum were obtained prior to the time of injection, together with serums taken two weeks after the clinics were completed and again five months later, and were to be tested in the respective laboratories. These records were also established and results received at the center. From them the distribution of antibody in this segment of the population in different parts of the country, the response to vaccine, the persistence of effect, and possibly information on the extent of natural exposure to poliomyelitis virus in the different areas during the study period as indicated by antibody changes could be determined.</span></p>
<div id="tbl-2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Distribution of Study Population, by Participation Status and Vaccination Status - Placebo Areas
</figcaption>
<div aria-describedby="tbl-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Study Population</th>
<th>No.</th>
<th>%</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Total in grades 1, 2, and 3</strong></td>
<td>749,236</td>
<td>100.0</td>
</tr>
<tr class="even">
<td><strong>Total requests to participate</strong></td>
<td>455,474</td>
<td>60.8</td>
</tr>
<tr class="odd">
<td>Complete series of injections</td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>- Vaccine</td>
<td>200,745</td>
<td>26.8</td>
</tr>
<tr class="odd">
<td>- Placebo</td>
<td>201,229</td>
<td>26.9</td>
</tr>
<tr class="even">
<td>Incomplete injections</td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>- Vaccine</td>
<td>8,484</td>
<td>1.1</td>
</tr>
<tr class="even">
<td>- Placebo</td>
<td>8,577</td>
<td>1.1</td>
</tr>
<tr class="odd">
<td><strong>Absent at first clinic or withdrew</strong></td>
<td>36,439</td>
<td>4.9</td>
</tr>
<tr class="even">
<td><strong>Number not requesting participation</strong></td>
<td>280,868</td>
<td>37.5</td>
</tr>
<tr class="odd">
<td><strong>Participation status not recorded</strong></td>
<td>12,894</td>
<td>1.7</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><span class="variables">The second phase in the evaluation was concerned with discovery and identification of all cases of poliomyelitis or suspected poliomyelitis in all children of the first, second, and third grades in the study areas. The various steps in the investigation of a case are: (1) physician’s diagnosis—report to local health department; (2) telegraphic report to vaccine evaluation center; (3) action of local health department, including (a) clinicoepidemiological investigation and report to vaccine evaluation center, form FT-6, (b) collection and shipment of laboratory specimens (or by laboratory) and notice to vaccine evaluation center, form FT-9, and (c) notification of physical therapist; (4) first muscle evaluation by physical therapist (10 to 20 days) and physician’s interpretation of patient’s status, form FT-7; (5) collection of convalescent serum for laboratory, form FT-9; (6) second muscle evaluation by physical therapist (50 to 70 days) and physician’s interpretation of patient’s entire illness, form FT-8; (7) report of virus isolation, tests of antibody titer, laboratory diagnosis, form FT-10; (8) establishment and application of criteria for diagnosis of individual patient; and (9) integration of all data into final vaccine evaluation center diagnosis. The criteria for diagnosis of poliomyelitis, for designation of a case as paralytic and its severity, and for the interpretation of laboratory results were carefully drawn.</span> In this we had the continued help of an advisory committee comprised of expert clinicians, virologists, biostatisticians, epidemiologists, and administrators. The information concerning each case was carefully reviewed and the diagnostic classification made without knowledge of its vaccination status so that objectivity was readily maintained. Inevitably, difficulties in decision were encountered when results from different pieces of data were not in agreement, but the effort was made to follow a consistent plan of interpretation.</p>
</section>
<section id="results" class="level1">
<h1>RESULTS</h1>
<p><span class="setting">The study period was defined as the period from two weeks after the time of the third injections in an area to Dec.&nbsp;31, 1954. The beginning was selected because it coincided generally with the time when second blood specimens were obtained for measurement of antigenic response to vaccine.</span> During the study period there were 1,013 cases reported to be poliomyelitis or suspected poliomyelitis; 428 in the total study population of placebo areas and 585 in the total study population of observed areas. With the criteria employed, 67.6% were classified as paralytic, 17.6% as nonparalytic, and 14.8% as not poliomyelitis or doubtful. There was no major difference in distribution of diagnoses in the two populations.</p>
<p>Table 3 shows the cases distributed according to the various segments of the total populations involved. It must be emphasized again that the evaluation is limited to a comparison of incidence in the vaccinated and in the established controls. The nonparticipating portions of the populations, that is, those who specifically refused to participate, are not additional controls. That decision was firmly established well in advance of the tabulation of results. The data are presented only because they are available and for completeness of reporting. The cases and rates per 100,000 of specific population are listed. In the placebo control areas there was a total of 82 cases reported among the 200,745 vaccinated and 162 among the 201,229 who received a placebo. The corresponding rates are 41 and 81—a ratio of 1:2; however, 25 and 20 cases, respectively, were classified as not poliomyelitis or doubtful. Thus, when the cases accepted as poliomyelitis are compared, there are 57 and 142, respectively, with rates of 28 and 71, a ratio of 1:2.5. When these are subdivided into paralytic and nonparalytic groups, no difference is observed between the incidence of nonparalytic cases among vaccinated and control persons. The sole significant difference, then, resides in the cases classified as paralytic poliomyelitis; there were 33 in the vaccinated group and 3.5 times as many, 115, in the placebo control group. In the observed control study, the number of controls is 3.3 times that of the inoculated; hence, for comparison the rates must be used. Here, again, there is no significant difference between the rates in nonparalytic cases or between the doubtful and not poliomyelitis groups in the vaccinated and control patients. The rates for paralytic cases are, however, 17 and 46 respectively — a ratio of 1:2.7. This possibility was an essential reason for establishing the strictly controlled placebo study. Moreover, the uninoculated — or refused — portion of the second grade in observed areas also had a lower rate than the designated controls who themselves were both “yes” and “no” participants. When the incidence rates in control and uninoculated groups combined are calculated for the placebo study and for the observed study, they are the same, 43.7 and 43.9 respectively. The differences disappear.</p>
<div id="tbl-3" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Summary of Study Cases by Diagnostic Class and Vaccination Status, Rate per 100,000
</figcaption>
<div aria-describedby="tbl-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 8%">
<col style="width: 5%">
<col style="width: 6%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th>Study Group</th>
<th style="text-align: right;">Subgroup</th>
<th style="text-align: right;">Study Population</th>
<th style="text-align: right;">All Reported Cases (No)</th>
<th style="text-align: right;">All Reported Cases (Rate)</th>
<th style="text-align: right;">Poliomyelitis Total (No)</th>
<th style="text-align: right;">Poliomyelitis Total (Rate)</th>
<th style="text-align: right;">Poliomyelitis Paralytic (No)</th>
<th style="text-align: right;">Poliomyelitis Paralytic (Rate)</th>
<th style="text-align: right;">Poliomyelitis Nonparalytic (No)</th>
<th style="text-align: right;">Poliomyelitis Nonparalytic (Rate)</th>
<th style="text-align: right;">Doubtful Or Not Poliomyelitis (No)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>All areas</td>
<td style="text-align: right;">total</td>
<td style="text-align: right;">1,829,916</td>
<td style="text-align: right;">1,013</td>
<td style="text-align: right;">55</td>
<td style="text-align: right;">863</td>
<td style="text-align: right;">47</td>
<td style="text-align: right;">685</td>
<td style="text-align: right;">37</td>
<td style="text-align: right;">178</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">150</td>
</tr>
<tr class="even">
<td>Placebo areas</td>
<td style="text-align: right;">total</td>
<td style="text-align: right;">749,236</td>
<td style="text-align: right;">428</td>
<td style="text-align: right;">57</td>
<td style="text-align: right;">358</td>
<td style="text-align: right;">48</td>
<td style="text-align: right;">270</td>
<td style="text-align: right;">36</td>
<td style="text-align: right;">88</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">70</td>
</tr>
<tr class="odd">
<td>Placebo areas</td>
<td style="text-align: right;">Vaccinated</td>
<td style="text-align: right;">200,745</td>
<td style="text-align: right;">82</td>
<td style="text-align: right;">41</td>
<td style="text-align: right;">57</td>
<td style="text-align: right;">28</td>
<td style="text-align: right;">33</td>
<td style="text-align: right;">16</td>
<td style="text-align: right;">24</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">25</td>
</tr>
<tr class="even">
<td>Placebo areas</td>
<td style="text-align: right;">Placebo</td>
<td style="text-align: right;">201,229</td>
<td style="text-align: right;">162</td>
<td style="text-align: right;">81</td>
<td style="text-align: right;">142</td>
<td style="text-align: right;">71</td>
<td style="text-align: right;">115</td>
<td style="text-align: right;">57</td>
<td style="text-align: right;">27</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">20</td>
</tr>
<tr class="odd">
<td>Placebo areas</td>
<td style="text-align: right;">Not inoculated<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></td>
<td style="text-align: right;">338,778</td>
<td style="text-align: right;">182</td>
<td style="text-align: right;">54</td>
<td style="text-align: right;">157</td>
<td style="text-align: right;">46</td>
<td style="text-align: right;">121</td>
<td style="text-align: right;">36</td>
<td style="text-align: right;">36</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">25</td>
</tr>
<tr class="even">
<td>Placebo areas</td>
<td style="text-align: right;">Incomplete vaccinations</td>
<td style="text-align: right;">8,484</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">24</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">24</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">—</td>
</tr>
<tr class="odd">
<td>Observed areas</td>
<td style="text-align: right;">total</td>
<td style="text-align: right;">1,080,680</td>
<td style="text-align: right;">585</td>
<td style="text-align: right;">54</td>
<td style="text-align: right;">505</td>
<td style="text-align: right;">47</td>
<td style="text-align: right;">415</td>
<td style="text-align: right;">38</td>
<td style="text-align: right;">90</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">80</td>
</tr>
<tr class="even">
<td>Observed areas</td>
<td style="text-align: right;">Vaccinated</td>
<td style="text-align: right;">221,998</td>
<td style="text-align: right;">76</td>
<td style="text-align: right;">34</td>
<td style="text-align: right;">56</td>
<td style="text-align: right;">25</td>
<td style="text-align: right;">38</td>
<td style="text-align: right;">17</td>
<td style="text-align: right;">18</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">20</td>
</tr>
<tr class="odd">
<td>Observed areas</td>
<td style="text-align: right;">Controls <a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a></td>
<td style="text-align: right;">725,173</td>
<td style="text-align: right;">439</td>
<td style="text-align: right;">61</td>
<td style="text-align: right;">391</td>
<td style="text-align: right;">54</td>
<td style="text-align: right;">330</td>
<td style="text-align: right;">46</td>
<td style="text-align: right;">61</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">48</td>
</tr>
<tr class="even">
<td>Observed areas</td>
<td style="text-align: right;">2nd grade not inoculated</td>
<td style="text-align: right;">123,605</td>
<td style="text-align: right;">66</td>
<td style="text-align: right;">53</td>
<td style="text-align: right;">54</td>
<td style="text-align: right;">44</td>
<td style="text-align: right;">43</td>
<td style="text-align: right;">35</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">12</td>
</tr>
<tr class="odd">
<td>Observed areas</td>
<td style="text-align: right;">Incomplete vaccinations</td>
<td style="text-align: right;">9,904</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">40</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">40</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">40</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div id="tbl-4" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4: Study Cases with Onset up to Nine Weeks from Date of first Inoculation, by Vaccination Status <a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a> - Placebo Areas
</figcaption>
<div aria-describedby="tbl-4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 7%">
<col style="width: 12%">
<col style="width: 2%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 7%">
<col style="width: 8%">
<col style="width: 9%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
</colgroup>
<thead>
<tr class="header">
<th>Group</th>
<th>Subgroup</th>
<th>Total</th>
<th>Virus Type 1 Recovered</th>
<th>Virus Type 2 Recovered</th>
<th>Virus Type 3 Recovered</th>
<th>Negative Isolation</th>
<th>Other Virus Recovered</th>
<th>Not Collected Or Not Done</th>
<th>Week 0</th>
<th>Week 1</th>
<th>Week 2</th>
<th>Week 3</th>
<th>Week 4</th>
<th>Week 5</th>
<th>Week 6</th>
<th>Week 7</th>
<th>Week 8</th>
<th>Week 9</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Vaccinates</td>
<td>Paralytic</td>
<td>2</td>
<td></td>
<td></td>
<td></td>
<td>2</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>1</td>
<td></td>
<td>1</td>
<td></td>
</tr>
<tr class="even">
<td>Vaccinates</td>
<td>Nonparalytic</td>
<td>1</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>1</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>1</td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>Vaccinates</td>
<td>Not poliomyelitis or doubtful</td>
<td>3</td>
<td></td>
<td></td>
<td></td>
<td>1</td>
<td></td>
<td>2</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>1</td>
<td>1</td>
<td></td>
<td>1</td>
</tr>
<tr class="even">
<td>Placebo</td>
<td>Paralytic</td>
<td>4</td>
<td></td>
<td></td>
<td>2</td>
<td>2</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>1</td>
<td>1</td>
<td></td>
<td>2</td>
<td></td>
</tr>
<tr class="odd">
<td>Placebo</td>
<td>Nonparalytic</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Placebo</td>
<td>Not poliomyelitis or doubtful</td>
<td>3<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a></td>
<td></td>
<td></td>
<td></td>
<td>1</td>
<td></td>
<td>2</td>
<td></td>
<td></td>
<td></td>
<td>1</td>
<td></td>
<td>1</td>
<td></td>
<td></td>
<td>1</td>
<td></td>
</tr>
<tr class="odd">
<td>Partial vaccinates</td>
<td>Paralytic</td>
<td>2</td>
<td>1</td>
<td></td>
<td></td>
<td>1</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>1</td>
<td></td>
<td>1<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Partial vaccinates</td>
<td>Nonparalytic</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>Partial vaccinates</td>
<td>Not poliomyelitis or doubtful</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>All other</td>
<td>Paralytic</td>
<td>8</td>
<td>1</td>
<td></td>
<td>2</td>
<td>1</td>
<td></td>
<td>4</td>
<td></td>
<td></td>
<td>1</td>
<td>1</td>
<td></td>
<td>1</td>
<td></td>
<td>1</td>
<td>3</td>
<td>1</td>
</tr>
<tr class="odd">
<td>All other</td>
<td>Nonparalytic</td>
<td>4</td>
<td></td>
<td></td>
<td>1</td>
<td>3</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>1</td>
<td>2</td>
<td>1</td>
</tr>
<tr class="even">
<td>All other</td>
<td>Not poliomyelitis or doubtful</td>
<td>5</td>
<td></td>
<td></td>
<td></td>
<td>5</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>4</td>
<td>1</td>
<td></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><em>Lack of Evidence of Provocation or Infection from Vaccination.</em> — It had been suggested that the placebo inoculations might exert some provocative influence toward paralytic poliomyelitis. Analysis of the data reveals no evidence of exaggerated incidence or localization of paralysis associated with inoculations. Further information is presented regarding the occurrence of poliomyelitis in the total study populations during the nine-week period from the beginning of vaccination to four weeks after the third injections in an area. There were 129 reported cases. As seen in tables 4 and 5, no distinctive difference in incidence in time of occurrence of cases appears in the vaccinated, placebo, or uninoculated groups of the placebo areas, or in the corresponding groups of the observed areas. The latter included many more southern states where poliomyelitis was already being reported at the time of vaccination, especially in Texas where half of the cases occurred (table 6). The number of cases in the first and third grade controls and in the vaccinated group is directly proportionate to the population. The tables also contain the results of efforts to isolate virus from the reported cases. From the four cases of paralytic poliomyelitis among those receiving vaccine, partial or complete series, type 1 virus was recovered once; the others were negative. Poliomyelitis virus was recovered only once from vaccinated persons in the observed areas, a type 2. From half of the paralytic cases in the control group in which tests were done, poliomyelitis virus was isolated: eight type 1 and four type 3. There were only two instances of poliomyelitis in associates of vaccinated persons during this nine-week period. The study member in New York state received the third injection of vaccine on June 17; the’ sibling developed nonparalytic poliomyelitis 26 days later, and 2 days later the vaccinated child developed poliomyelitis with minimal paralytic signs; no virus was recovered. In Texas, a child received his third injection of vaccine on June 15, and 21 days later had the onset of mild bulbar poliomyelitis, but no virus was recovered. The sibling had his onset on the same day, with nonparalytic polio myelitis and negative virus studies. There were three instances of similar nature in the placebo group, three in the uninoculated of the placebo study areas, three in the controls, and one in the nonparticipating group of observed areas. There is, therefore, no indication of undue transmission of poliomyelitis virus from vaccinated persons in this period to other members of the household.</p>
<div id="tbl-5" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-5-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5: Study Cases with Onset up to Nine Weeks from Date of First Inoculation, by Vaccination Status<a href="#fn7" class="footnote-ref" id="fnref7" role="doc-noteref"><sup>7</sup></a> — Observed Areas
</figcaption>
<div aria-describedby="tbl-5-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 7%">
<col style="width: 12%">
<col style="width: 2%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 7%">
<col style="width: 8%">
<col style="width: 9%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
</colgroup>
<thead>
<tr class="header">
<th>Group</th>
<th>Subgroup</th>
<th>Total</th>
<th>Virus Type 1</th>
<th>Virus Type 2</th>
<th>Virus Type 3</th>
<th>Negative Isolation</th>
<th>Other Virus Recovered</th>
<th>Not Collected Or Not Done</th>
<th>Week 0</th>
<th>Week 1</th>
<th>Week 2</th>
<th>Week 3</th>
<th>Week 4</th>
<th>Week 5</th>
<th>Week 6</th>
<th>Week 7</th>
<th>Week 8</th>
<th>Week 9</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Vaccinates</td>
<td>Paralytic</td>
<td>7</td>
<td></td>
<td></td>
<td></td>
<td>6</td>
<td></td>
<td>1</td>
<td></td>
<td>1</td>
<td></td>
<td>1</td>
<td></td>
<td></td>
<td>1</td>
<td>1</td>
<td>3</td>
<td></td>
</tr>
<tr class="even">
<td>Vaccinates</td>
<td>Nonparalytic</td>
<td>5</td>
<td></td>
<td>1</td>
<td></td>
<td>3</td>
<td>1</td>
<td></td>
<td></td>
<td></td>
<td>1</td>
<td></td>
<td>1</td>
<td>1</td>
<td>1</td>
<td></td>
<td>1</td>
<td></td>
</tr>
<tr class="odd">
<td>Vaccinates</td>
<td>Not poliomyelitis or doubtful</td>
<td>6</td>
<td></td>
<td></td>
<td></td>
<td>4</td>
<td></td>
<td>2</td>
<td></td>
<td></td>
<td></td>
<td>2</td>
<td></td>
<td></td>
<td>1</td>
<td>2</td>
<td>1</td>
<td></td>
</tr>
<tr class="even">
<td>Control</td>
<td>Paralytic</td>
<td>35</td>
<td>8</td>
<td></td>
<td>4</td>
<td>12</td>
<td></td>
<td>11</td>
<td>3</td>
<td>3</td>
<td>4</td>
<td>2</td>
<td>4</td>
<td>3</td>
<td>6</td>
<td>1</td>
<td>5</td>
<td>4</td>
</tr>
<tr class="odd">
<td>Control</td>
<td>Nonparalytic</td>
<td>15</td>
<td></td>
<td></td>
<td>1</td>
<td>4</td>
<td></td>
<td>10</td>
<td>2</td>
<td>1</td>
<td></td>
<td></td>
<td>4</td>
<td>1</td>
<td>2</td>
<td>2</td>
<td>3</td>
<td></td>
</tr>
<tr class="even">
<td>Control</td>
<td>Not poliomyelitis or doubtful</td>
<td>9</td>
<td></td>
<td></td>
<td></td>
<td>8</td>
<td></td>
<td>1</td>
<td>1</td>
<td>2</td>
<td></td>
<td>1</td>
<td>1</td>
<td></td>
<td></td>
<td>1</td>
<td>2</td>
<td>1</td>
</tr>
<tr class="odd">
<td>Partial vaccinates</td>
<td>Paralytic</td>
<td>4</td>
<td></td>
<td></td>
<td></td>
<td>3</td>
<td></td>
<td>1</td>
<td></td>
<td>1</td>
<td></td>
<td>1</td>
<td></td>
<td>2</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Partial vaccinates</td>
<td>Nonparalytic</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>Partial vaccinates</td>
<td>Not poliomyelitis or doubtful</td>
<td>4</td>
<td></td>
<td></td>
<td></td>
<td>4</td>
<td></td>
<td></td>
<td></td>
<td>1</td>
<td>1</td>
<td></td>
<td>1</td>
<td>1</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>All other</td>
<td>Paralytic</td>
<td>5</td>
<td>1</td>
<td></td>
<td>1</td>
<td>2</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>1</td>
<td>1</td>
<td></td>
<td></td>
<td></td>
<td>3</td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>All other</td>
<td>Nonparalytic</td>
<td>5</td>
<td></td>
<td></td>
<td></td>
<td>2</td>
<td></td>
<td>3</td>
<td>1</td>
<td>1</td>
<td></td>
<td>1</td>
<td>1</td>
<td>1</td>
<td></td>
<td>1</td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>All other</td>
<td>Not poliomyelitis or doubtful</td>
<td>2</td>
<td></td>
<td></td>
<td></td>
<td>2</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>1</td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div id="tbl-6" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-6-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6: Study Cases with Onset up to Nine Weeks from Date of First Inoculation, by Vaccination Status<a href="#fn8" class="footnote-ref" id="fnref8" role="doc-noteref"><sup>8</sup></a> - Texas
</figcaption>
<div aria-describedby="tbl-6-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 7%">
<col style="width: 12%">
<col style="width: 2%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 7%">
<col style="width: 8%">
<col style="width: 9%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
</colgroup>
<thead>
<tr class="header">
<th>Group</th>
<th>Subgroup</th>
<th>Total</th>
<th>Virus Type 1</th>
<th>Virus Type 2</th>
<th>Virus Type 3</th>
<th>Negative Isolation</th>
<th>Not Collected Or Not Done</th>
<th>Week 0</th>
<th>Week 1</th>
<th>Week 2</th>
<th>Week 3</th>
<th>Week 4</th>
<th>Week 5</th>
<th>Week 6</th>
<th>Week 7</th>
<th>Week 8</th>
<th>Week 9</th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Vaccinates</td>
<td>Paralytic</td>
<td>5</td>
<td></td>
<td></td>
<td></td>
<td>5</td>
<td></td>
<td>1</td>
<td></td>
<td>1</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>1</td>
<td>3</td>
<td></td>
</tr>
<tr class="even">
<td>Vaccinates</td>
<td>Nonparalytic</td>
<td>3</td>
<td></td>
<td></td>
<td></td>
<td>3</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>1</td>
<td></td>
<td>1</td>
<td></td>
<td>1</td>
<td></td>
<td>1</td>
<td></td>
</tr>
<tr class="odd">
<td>Vaccinates</td>
<td>Not poliomyelitis or doubtful</td>
<td>2</td>
<td></td>
<td></td>
<td></td>
<td>2</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>1</td>
<td></td>
<td></td>
<td></td>
<td>1</td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Control</td>
<td>Paralytic</td>
<td>16</td>
<td>5</td>
<td></td>
<td>2</td>
<td>6</td>
<td></td>
<td>3</td>
<td></td>
<td>1</td>
<td></td>
<td>2</td>
<td>2</td>
<td>2</td>
<td>4</td>
<td>1</td>
<td>2</td>
<td>2</td>
</tr>
<tr class="odd">
<td>Control</td>
<td>Nonparalytic</td>
<td>10</td>
<td></td>
<td></td>
<td></td>
<td>2</td>
<td></td>
<td>8</td>
<td>2</td>
<td>1</td>
<td></td>
<td></td>
<td>1</td>
<td>1</td>
<td>2</td>
<td>1</td>
<td>3</td>
<td></td>
</tr>
<tr class="even">
<td>Control</td>
<td>Not poliomyelitis or doubtful</td>
<td>4</td>
<td></td>
<td></td>
<td></td>
<td>3</td>
<td></td>
<td>1</td>
<td>1</td>
<td>1</td>
<td></td>
<td></td>
<td>1</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>1</td>
</tr>
<tr class="odd">
<td>Partial vaccinates</td>
<td>Paralytic</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Partial vaccinates</td>
<td>Nonparalytic</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>Partial vaccinates</td>
<td>Not poliomyelitis or doubtful</td>
<td>1</td>
<td></td>
<td></td>
<td></td>
<td>1</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>1</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>All other</td>
<td>Paralytic</td>
<td>1</td>
<td>1</td>
<td></td>
<td></td>
<td>2</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>1</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>All other</td>
<td>Nonparalytic</td>
<td>2</td>
<td></td>
<td></td>
<td></td>
<td>2</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>1</td>
<td>1</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>All other</td>
<td>Not poliomyelitis or doubtful</td>
<td>2</td>
<td></td>
<td></td>
<td></td>
<td>2</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>1</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><em>Distribution of Paralytic and Laboratory Confirmed Cases.</em> - The subsequent analyses of case distribution were directed toward the combining of clinical and laboratory data that enhance the reliability of diagnosis. A summary of these progessive stages with accompanying estimates of effectiveness in the two types of study are given in table 7. In the placebo areas there was a distinct trend for the differences in ratio between vaccinated and controls to increase as the severity of paralytic involvement increased. In spinal paralytic cases of minimal degrees of involvement the difference was only 2:1, suggesting that here, too, cases that were not specific poliomyelitis virus infections were included in these clinical classifications. In the more severe classes, how¬ ever, the distinction became quite marked, emphasizing the possibility that the vaccine exhibited its major influence in preventing significant muscular impairment. The difference in rates for bulbospinal cases was pronounced and highly significant.</p>
<p>The same trend occurs among spinal paralytic cases in observed areas, but the difference between total bulbospinal rates is less, apparently owing to the lack of effect in cases with minimal paralytic ratings. The limited number of cases, however, can significantly limit the degree of numerical agreement in the two studies. Analysis of paralytic cases that were designated by virus isolation, serology, or virus in family associates as specific infections with the known types of poliomyelitis virus was then undertaken. This obviously reduces again the number of cases admitted to consideration. It is seen, however, that with these criteria, the estimated effect of vaccine was the same in spinal paralytic cases of both placebo and observed study areas. However, the discrepancy between the bulbospinal cases in the two studies persists.</p>
<div id="tbl-7" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-7-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;7: Estimates of Effectiveness of Vaccine at Successive Stages of Analysis
</figcaption>
<div aria-describedby="tbl-7-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 8%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 9%">
<col style="width: 10%">
<col style="width: 3%">
</colgroup>
<thead>
<tr class="header">
<th>Diagnostic Classification</th>
<th>Placebo, Vaccinated, No Cases</th>
<th>Placebo, Controls , No Cases</th>
<th>Placebo Significance Level</th>
<th>Placebo, % Effectiveness Estimate</th>
<th>Placebo, %Effectiveness Lower Limit</th>
<th>Observed, Vaccinated, No Cases</th>
<th>Observed, Controls, No Cases</th>
<th>Observed, Significance Level</th>
<th>Observed, %Effectiveness Estimate</th>
<th>Observed, % Effectiveness Lower Limit</th>
<th>Source Of Data</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Total cases reported <a href="#fn9" class="footnote-ref" id="fnref9" role="doc-noteref"><sup>9</sup></a></td>
<td>82</td>
<td>162</td>
<td>&lt;0.001</td>
<td>49</td>
<td>36</td>
<td>76</td>
<td>439</td>
<td>&lt;0.001</td>
<td>44</td>
<td>32</td>
<td>Table 3</td>
</tr>
<tr class="even">
<td>Total poliomyelitis</td>
<td>57</td>
<td>142</td>
<td>&lt;0.001</td>
<td>60</td>
<td>49</td>
<td>56</td>
<td>391</td>
<td>&lt;0.001</td>
<td>54</td>
<td>32</td>
<td></td>
</tr>
<tr class="odd">
<td>All paralytic</td>
<td>33</td>
<td>115</td>
<td>&lt;0.001</td>
<td>72</td>
<td>61</td>
<td>38</td>
<td>330</td>
<td>&lt;0.001</td>
<td>62</td>
<td>51</td>
<td></td>
</tr>
<tr class="even">
<td>All nonparalytic<a href="#fn10" class="footnote-ref" id="fnref10" role="doc-noteref"><sup>10</sup></a></td>
<td>24</td>
<td>27</td>
<td>NS</td>
<td></td>
<td></td>
<td>18</td>
<td>61</td>
<td>NS</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>Paralytic-spinal</td>
<td>28</td>
<td>70</td>
<td>&lt;0.001</td>
<td>60</td>
<td>39</td>
<td>20</td>
<td>199</td>
<td>&lt;0.001</td>
<td>66</td>
<td>53</td>
<td>Tables 3a, b<a href="#fn11" class="footnote-ref" id="fnref11" role="doc-noteref"><sup>11</sup></a></td>
</tr>
<tr class="even">
<td>Bulbospinal</td>
<td>2</td>
<td>36</td>
<td>&lt;0.001</td>
<td>94</td>
<td>81</td>
<td>15</td>
<td>100</td>
<td>&lt;0.001</td>
<td>50</td>
<td>19</td>
<td></td>
</tr>
<tr class="odd">
<td>Laboratory confirmed</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Spinal</td>
<td>8</td>
<td>45</td>
<td>&lt;0.001</td>
<td>82</td>
<td>65</td>
<td>7</td>
<td>127</td>
<td>&lt;0.001</td>
<td>83</td>
<td>64</td>
<td>Tables 5a, b‡</td>
</tr>
<tr class="odd">
<td>Bulbospinal</td>
<td>2</td>
<td>23</td>
<td>&lt;0.001</td>
<td>91</td>
<td>68</td>
<td>9</td>
<td>71</td>
<td>&lt;0.01</td>
<td>60</td>
<td>23</td>
<td></td>
</tr>
<tr class="even">
<td>All virus positive</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>Total</td>
<td>15</td>
<td>70</td>
<td>&lt;0.001</td>
<td>80</td>
<td>65</td>
<td>20</td>
<td>210</td>
<td>&lt;0.001</td>
<td>69</td>
<td>36</td>
<td>Tables 6a, b‡</td>
</tr>
<tr class="even">
<td>Type 1</td>
<td>13</td>
<td>39</td>
<td>&lt;0.001</td>
<td>68</td>
<td>41</td>
<td>14</td>
<td>114</td>
<td>&lt;0.001</td>
<td>62</td>
<td>33</td>
<td></td>
</tr>
<tr class="odd">
<td>Type 2</td>
<td>0</td>
<td>6</td>
<td>&lt;0.05</td>
<td>100</td>
<td>33</td>
<td>2</td>
<td>34</td>
<td>&lt;0.01</td>
<td>80</td>
<td>33</td>
<td></td>
</tr>
<tr class="even">
<td>Type 3</td>
<td>2</td>
<td>25</td>
<td>&lt;0.001</td>
<td>92</td>
<td>72</td>
<td>4</td>
<td>62</td>
<td>&lt;0.001</td>
<td>78</td>
<td>47</td>
<td></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Finally, the distribution was studied of all cases, paralytic and nonparalytic, from whom a specific poliomyelitis virus was isolated. In placebo areas an effectiveness of 68% was estimated against type 1, and 90% or more against types 2 and 3. In observed areas the trend was the same but lower. What, then, can be given as the effectiveness of vaccine? The calculations pre sented in the table appear to be valid estimates from the summarized data. Subsequent review has not revealed significant error. It is fully recognized that larger numbers would have created greater security, but the data obtained are unprejudiced appraisals. The strictly controlled placebo study provides the data in which there is greater confidence than those from the observed control study. In fact, the results from the observed areas would be more difficult to interpret if they had not followed the trend of those obtained in the placebo study. The lesser effect seen against type 1 virus is in accord with the lesser antigenic effect of a number of the preparations of vaccine measured against type 1 virus. But taking the composite results against laboratory confirmed cases of paralytic poliomyelitis an effectiveness of 80 to 90% was observed in the placebo study areas and 60 to 80% in observed study areas. It must be emphasized that the results presented apply to the circumstances in effect for the 1954 studies during which intensive efforts were made to obtain as complete and uniform data as conditions of study would permit.</p>
<p>There are questions arising from the data to which there is yet no ready answer. The incidence of paralytic cases in the 6-year-old group did not appear significantly different in vaccinated and controls of the placebo areas. It can only be pointed out at the present that when these cases were considered in terms of virus isolation, there were four cases of type 1 in each group, but there were no type 2 or type 3 cases in the vaccinated while one and five cases, respectively, occurred in the controls. Study of this problem is continuing.</p>
</section>
<section id="summary" class="level1">
<h1>SUMMARY</h1>
<p>This review has been directed to a further summary of the report of the evaluation of the 1954 field trial of poliomyelitis vaccine. The data appear on further examination to retain their validity. Possible harmful effects of the poliomyelitis vaccine were not indicated by the data. Again, the definition of controls and the value of strictly controlled studies is emphasized. It is apparent that the medical profession at large needs further preparation for effective participation in the investigation of health problems in which their activities as physicians contribute the essential data.</p>
</section>
<section id="end-notes" class="level1">
<h1>End Notes</h1>
<ul>
<li><p>From the Department of Epidemiology and the Virus Laboratory, School of Public Health, and the Vaccine Evaluation Center, University of Michigan.</p></li>
<li><p>Read in the Panel Discussion on Prospects for the Control of Poliomyelitis before the Joint Meeting of the Section on Pediatrics and the Section on Preventive and Industrial Medicine and Public Health at the 104th Annual Meeting of the American Medical Association, Atlantic City, June 7, 1955.</p></li>
<li><p>This study was aided by a grant from the National Foundation for Infantile Paralysis, Inc.</p></li>
</ul>


</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>Francis, T., Jr., and others: Evaluation of the 1954 Field Trials of Poliomyelitis Vaccine: Summary Report, Am. J. Pub. Health 45:1-63 (May, pt.&nbsp;2) 1955.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>Includes 8577 children who received one or two injections of placebo.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>1st and 3rd grade total population<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>Date of first inoculation in school used for uninoculated children.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>Partial placebo, one case<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p>Doubtful facial<a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn7"><p>Date of first inoculation in school used for uninoculated children.<a href="#fnref7" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn8"><p>Date of first inoculation in school used for uninoculated children. No viruses other than the poliomyelitis virus were recovered. <a href="#fnref8" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn9"><p>Because of small numbers the bulbar and fatal cases are omitted. All fatal cases occurred in controls.<a href="#fnref9" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn10"><p>Nonparalytic case distribution difference not significant at any stage of analysis.<a href="#fnref10" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn11"><p>Francis, T., Jr., and others: Evaluation of the 1954 Field Trials of Poliomyelitis Vaccine: Summary Report, Am. J. Pub. Health 45:1-63 (May, pt.&nbsp;2) 1955.<a href="#fnref11" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/unl-statistics\.github\.io\/stat349");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© Copyright 2025, Susan Vanderplas</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/unl-statistics/stat349/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>